using QuantTrading.Core.Interfaces;
using QuantTrading.Core.Models;

namespace QuantTrading.Worker;

public class TradingWorker : BackgroundService
{
    private readonly ILogger<TradingWorker> _logger;
    private readonly IStrategyEngine _strategyEngine;

    public TradingWorker(ILogger<TradingWorker> logger, IStrategyEngine strategyEngine)
    {
        _logger = logger;
        _strategyEngine = strategyEngine;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogInformation("Trading Worker starting at: {time}", DateTimeOffset.Now);

        // Subscribe to signals generated by the engine
        _strategyEngine.OnSignalGenerated += (signal) =>
        {
            _logger.LogWarning("!!! SIGNAL GENERATED: {strategy} for {ticker} at {price} (Size: {size})",
                signal.Strategy, signal.Ticker, signal.EntryPrice, signal.PositionSize);
        };

        // Main Loop: In a real scenario, this would listen to gRPC MarketData stream
        while (!stoppingToken.IsCancellationRequested)
        {
            // Simulation of receiving data
            // await Task.Delay(1000, stoppingToken);
            await Task.Yield();
        }
    }
}
